#pragma once
#include "Phynx/Core/Core.h"

#define PX_KEY_A		    (1)
#define PX_KEY_B		    (2)
#define PX_KEY_C		    (3)
#define PX_KEY_D		    (4)
#define PX_KEY_E		    (5)
#define PX_KEY_F		    (6)
#define PX_KEY_G		    (7)
#define PX_KEY_H		    (8)
#define PX_KEY_I		    (9)
#define PX_KEY_J		    (10)
#define PX_KEY_K		    (11)
#define PX_KEY_L		    (12)
#define PX_KEY_M		    (13)
#define PX_KEY_N		    (14)
#define PX_KEY_O		    (15)
#define PX_KEY_P		    (16)
#define PX_KEY_Q		    (17)
#define PX_KEY_R		    (18)
#define PX_KEY_S		    (19)
#define PX_KEY_T		    (20)
#define PX_KEY_U		    (21)
#define PX_KEY_V		    (22)
#define PX_KEY_W		    (23)
#define PX_KEY_X		    (24)
#define PX_KEY_Y		    (25)
#define PX_KEY_Z		    (26)

// Mouse keys
#define PX_MOUSE_LEFT		BIT(27)
#define PX_MOUSE_RIGHT		BIT(28)
#define PX_MOUSE_MIDDLE		BIT(29)
