#pragma once
#include "Phynx/Core/Core.h"

#define PX_KEY_A		    BIT(1)
#define PX_KEY_B		    BIT(2)
#define PX_KEY_C		    BIT(3)
#define PX_KEY_D		    BIT(4)
#define PX_KEY_E		    BIT(5)
#define PX_KEY_F		    BIT(6)
#define PX_KEY_G		    BIT(7)
#define PX_KEY_H		    BIT(8)
#define PX_KEY_I		    BIT(9)
#define PX_KEY_J		    BIT(10)
#define PX_KEY_K		    BIT(11)
#define PX_KEY_L		    BIT(12)
#define PX_KEY_M		    BIT(13)
#define PX_KEY_N		    BIT(14)
#define PX_KEY_O		    BIT(15)
#define PX_KEY_P		    BIT(16)
#define PX_KEY_Q		    BIT(17)
#define PX_KEY_R		    BIT(18)
#define PX_KEY_S		    BIT(19)
#define PX_KEY_T		    BIT(20)
#define PX_KEY_U		    BIT(21)
#define PX_KEY_V		    BIT(22)
#define PX_KEY_W		    BIT(23)
#define PX_KEY_X		    BIT(24)
#define PX_KEY_Y		    BIT(25)
#define PX_KEY_Z		    BIT(26)

// Mouse keys
#define PX_MOUSE_LEFT		BIT(27)
#define PX_MOUSE_RIGHT		BIT(28)
#define PX_MOUSE_MIDDLE		BIT(29)
